// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEhCndsjjILsDx1gF47Vihj9oermwCHbo',
    appId: '1:913439117784:web:f86d643873c2345cef62ad',
    messagingSenderId: '913439117784',
    projectId: 'house-platform-78131',
    authDomain: 'house-platform-78131.firebaseapp.com',
    storageBucket: 'house-platform-78131.appspot.com',
    measurementId: 'G-G4K0QX1890',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhdDPZoAFW_hM_vCYrPrsgaC2SnOfoh0Y',
    appId: '1:913439117784:android:ad1e4e8940bb08a1ef62ad',
    messagingSenderId: '913439117784',
    projectId: 'house-platform-78131',
    storageBucket: 'house-platform-78131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK70aKNn54Mzc4QpcS-2pm_PGTfs_g_Ms',
    appId: '1:913439117784:ios:b855e57621452e7bef62ad',
    messagingSenderId: '913439117784',
    projectId: 'house-platform-78131',
    storageBucket: 'house-platform-78131.appspot.com',
    iosBundleId: 'house.estates.estatesHouse',
  );
}
